src/commands/metrics.rs: Stupid PoC to fix the compiler errors
We need a better solution here - otherwise it would be better to just
drop async here since this locking makes it pointless.

Anyway, the PoC should be ready soon:
error: could not compile `butido` due to 4 previous errors